services:
  mssql:
    container_name: ates
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ""
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - microservices-net
    restart: unless-stopped
networks:
  microservices-net:
    driver: bridge

volumes:
  mssql_data:
